version: '3.8'
services:

  trino:
    image: 'trinodb/trino:latest'
    ports: [ '8080:8080' ]
    env_file: [ ./etc/.env ]
    volumes: [ ./etc/trino:/usr/lib/trino/etc:rw ]
    depends_on:
      - hive-metastore
      - minio

  mariadb:
    image: mariadb:10.5.8
    ports: [ '3306:3306' ]
    env_file: [ ./etc/.env ]
    volumes:
      - ./var/mariadb:/var/lib/mysql
      #- ./etc/mariadb:/etc/mysql/conf.d

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./etc/metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    env_file: [ ./etc/.env ]
    depends_on:
      - mariadb

  minio:
    hostname: minio
    image: 'minio/minio'
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - ./var/minio:/data
    env_file: [ ./etc/.env ]
    command: 'server --address ":9000" --console-address ":9001" /data'

  s3cmd:
    image: 'd3fk/s3cmd:latest'
    volumes:
      - ./etc/s3cmd/minio.s3cfg:/root/.s3cfg
    profiles:
      - cli
    env_file: [ ./etc/.env ]
    depends_on:
      - minio
    command: 's3cmd --config /root/.s3cfg --configure'